# k Vecinos más cercanos

## Ejemplo I

En este ejemplo, usamos un kernel lineal para clasificar un problema no linealmente separable. El resultado es una mala clasificación, no por un problema de la SVM, sino del kernel utilizado.

In [2]:
# Importamos los módulos necesarios
import numpy as np
import pandas as pd
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

# Leemos los datos que usaremos
points =  pd.read_csv("https://raw.githubusercontent.com/jcobayliss/TC3002B-M2/refs/heads/main/datasets/points.csv")

# Separamos las variables independientes de la dependiente
X = points.drop("Class", axis = 1)
y = points["Class"]

# Dividimos los datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.60, random_state = 54321)

# Creamos un modelo de clasificación usando el algoritmo de k-vecinos más cercanos
model = neighbors.KNeighborsClassifier(3, weights = "uniform")

# Entrenamos el modelo usando los datos de entrenamiento
model.fit(X_train, y_train)

# Realizamos la predicción usando los datos de prueba
prediction = model.predict(X_test)

# Generamos la matriz de confusión
confusion_matrix(y_test, prediction)

array([[81,  1],
       [11, 90]])

## Ejemplo II

Es importante tener en cuanta que el algoritmo de $k$ vecinos más cercanos requiere que todas las variables independientes sean numéricas y en rangos similares. Esto nos obliga a escalar las variables para prevenir resultados incorrectos.

En este ejemplo, las variables independientes tienen rangos significativamente diferentes, provocando que el algoritmo sea incapaz de aprender correctamente el patrón en los datos.

In [3]:
# Importamos los módulos necesarios
import numpy as np
import pandas as pd
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

# Leemos los datos que usaremos
points =  pd.read_csv("https://raw.githubusercontent.com/jcobayliss/TC3002B-M2/refs/heads/main/datasets/distance.csv")

# Separamos las variables independientes de la dependiente
X = points.drop("Output", axis = 1)
y = points["Output"]

# Dividimos los datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.60, random_state = 54321)

# Creamos un modelo de clasificación usando el algoritmo de k-vecinos más cercanos
model = neighbors.KNeighborsClassifier(5, weights = "uniform")

# Entrenamos el modelo usando los datos de entrenamiento
model.fit(X_train, y_train)

# Realizamos la predicción usando los datos de prueba
prediction = model.predict(X_test)

# Generamos la matriz de confusión
confusion_matrix(y_test, prediction)

array([[34, 25],
       [32, 29]])

## Ejemplo III

Para evitar el comportamiento errático observado en el ejemplo anterior, es indispensable escalar las variables antes de ejecutar el algoritmo de $k$ vecinos más cercanos.

In [4]:
import numpy as np
import pandas as pd
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

# Leemos los datos que usaremos
points =  pd.read_csv("https://raw.githubusercontent.com/jcobayliss/TC3002B-M2/refs/heads/main/datasets/distance.csv")

# Separamos las variables independientes de la dependiente
X = points.drop("Output", axis = 1)
y = points["Output"]

# Dividimos los datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.60, random_state = 54321)

# Creamos un escalador de datos
scaler = StandardScaler()

# Se ajusta el escalador usando únicamente los datos de entrenamiento
scaler.fit(X_train)

# Escalamos las variables independientes del entrenamiento y prueba
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# Creamos un modelo de clasificación usando el algoritmo de k-vecinos más cercanosmodel = neighbors.KNeighborsClassifier(5, weights = "uniform")

# Entrenamos el modelo usando los datos de entrenamiento
model.fit(X_train, y_train)

# Realizamos la predicción usando los datos de prueba
prediction = model.predict(X_test)

# Generamos la matriz de confusión
confusion_matrix(y_test, prediction)

array([[58,  1],
       [ 1, 60]])